name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Cache
      id: cache
      uses: actions/cache@v4.0.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/nasm
        # An explicit key for restoring and saving the cache
        key: nasm-v1.5.1
        # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        # restore-keys: # optional
        # The chunk size used to split up large files during upload, in bytes
        # upload-chunk-size: # optional
        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
        # enableCrossOsArchive: # optional, default is false
        # Fail the workflow if cache entry is not found
        # fail-on-cache-miss: # optional, default is false
        # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
        # lookup-only: # optional, default is false
        # Run the post step to save the cache even if another step before fails
        # save-always: # optional, default is false
    - name: Set up NASM
      if: steps.cache.outputs.cache-hit != 'true'
      uses: ilammy/setup-nasm@v1.5.1
    - name: test contar 1
      id: test-contar-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test contar 1
        setup-command: 'make main'
        command: "./test.sh"
        input: '1'
        expected-output: '1'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: test contar 2
      id: test-contar-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test contar 2
        setup-command: make
        command: "./test.sh"
        input: '2'
        expected-output: '2'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: test contar 3
      id: test-contar-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test contar 3
        setup-command: make
        command: "./test.sh"
        input: '3'
        expected-output: '3'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: test contar 4
      id: test-contar-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test contar 4
        setup-command: make
        command: "./test.sh"
        input: '4'
        expected-output: '4'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CONTAR-1_RESULTS: "${{steps.test-contar-1.outputs.result}}"
        TEST-CONTAR-2_RESULTS: "${{steps.test-contar-2.outputs.result}}"
        TEST-CONTAR-3_RESULTS: "${{steps.test-contar-3.outputs.result}}"
        TEST-CONTAR-4_RESULTS: "${{steps.test-contar-4.outputs.result}}"
      with:
        runners: test-contar-1,test-contar-2,test-contar-3,test-contar-4
