name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Cache
      id: cache
      uses: actions/cache@v4.0.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/nasm
        # An explicit key for restoring and saving the cache
        key: nasm-v1.5.1
        # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        # restore-keys: # optional
        # The chunk size used to split up large files during upload, in bytes
        # upload-chunk-size: # optional
        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
        # enableCrossOsArchive: # optional, default is false
        # Fail the workflow if cache entry is not found
        # fail-on-cache-miss: # optional, default is false
        # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
        # lookup-only: # optional, default is false
        # Run the post step to save the cache even if another step before fails
        # save-always: # optional, default is false
    - name: Set up NASM
      if: steps.cache.outputs.cache-hit != 'true'
      uses: ilammy/setup-nasm@v1.5.1
    - name: hello world test
      id: hello-world-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: hello world test
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-WORLD-TEST_RESULTS: "${{steps.hello-world-test.outputs.result}}"
      with:
        runners: hello-world-test
